# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
    - finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: manipulator_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
pos_controller:
  type: position_controllers/JointPositionController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
  gains:
    iiwa_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    iiwa_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1